### ISSUE TITLE
Control number of iterations in undistort()

### ISSUE THREAD

**Issue by jerry73204** [strawlab/opencv-ros-camera#6]
I see the `undistort()` method runs fixed-point method in 5 iterations. I'm sure if 5 times is sufficient. Could we expose a parameter to control the number of iterations, such as `undistort_ext(pixels, n_iterations)`? 
https://docs.rs/opencv-ros-camera/0.5.1/src/opencv_ros_camera/lib.rs.html#401-409

**Comment by astraw** [comment]
Yes, this is reasonable. If we do this, I think we should also add an alternative of testing for convergence with a specified epsilon. [OpenCV allows both now](https://github.com/opencv/opencv/blob/master/modules/calib3d/src/undistort.dispatch.cpp#L371-L416). (In OpenCV 3.2, they were fixed at 5 iterations).

Can I convince you to make a first implementation? I would then check it and hopefully merge it. I suggest to keep the existing API untouched and add this as new functionality, but depending how things go, we could revisit this.

**Comment by astraw** [comment]
This was closed by #7.
